name: Check URLs are resolvable

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install requests pyyaml

      - name: Check URLS
        run: python scripts/check_links.py