name: Semantic uplift

on:
  workflow_dispatch:

jobs:
  uplift:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/opengeospatial/ogc-na-tools.git
      - name: Process files
        env:
          DB_USERNAME: ${{ secrets.UPLOAD_GRAPH_STORE_USERNAME }}
          DB_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
        run: |
          python -m ogc.na.ingest_json --batch --skip-on-missing-context --all \
            --json-ld --ttl --work-dir . --domain-config .ogc/catalog.ttl
          python -m ogc.na.update_vocabs -w . .ogc/catalog.ttl --use-git-status \
            --update --graph-store https://defs-dev.opengis.net/fuseki-hosted/data
