name: Semantic uplift

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - jupyter/**
      - '**.py'
      - '**.md'
      - assets/**

jobs:
  uplift:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/opengeospatial/ogc-na-tools.git
      - name: Process files
        env:
          DB_USERNAME: ${{ secrets.UPLOAD_GRAPH_STORE_USERNAME }}
          DB_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
        run: |
          python -m ogc.na.ingest_json --batch --skip-on-missing-context --all \
            --ttl --work-dir ./rainbow-data --domain-config rainbow-data/catalog.ttl
          python -m ogc.na.update_vocabs -w ./rainbow-data rainbow-data/catalog.ttl --use-git-status \
            --update --graph-store https://defs-hosted.opengis.net/fuseki-hosted/data
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '**/*.ttl'

  check-links:
    if: false # disable
    uses: ./.github/workflows/check-links.yml
    needs: uplift
